[package]
name = "fetchy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nixinfo = "0.2.8"
ansi_term = "0.12.1"